export { getNewsAsync } from './get-news'
export { getNewsForSitemap } from './get-news-for-sitemap'
export { getNewsPost } from './get-news-post'
export { getNewsTotalCount } from './get-news-total-count'
export { getPinnedNews } from './get-pinned-news'
